### ISSUE TITLE
Completing the initial refactor

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe-core#1]
The following are items to consider/implement ahead of beginning integration back into thebe:

 * [x] get ipywidgets working again
 * [x] clean up around the `ipywidgets` support - perhaps just centralizing the code 
 * [x] error handling on notebook runs, capture last error or stop execution on error
 * [x] ability to keep controls disabled until kernel is live
 * [x] js API - IN PROGRESS
   * [x] provide promise based signals, with demo for discussion
 * [ ] executablebooks/thebe#563
 * [x] review thebe features/options and ensure JS api can support them
 * [x] executablebooks/thebe-core#9
 * [x] executablebooks/thebe-core#10

**Comment by stevejpurves** [comment]
Closing, track work in https://github.com/executablebooks/thebe
