### ISSUE TITLE
Integrate back into `thebe` and archive `thebe-core`

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe-core#15]
### Context

This repo was a refactor of the core thebe functionality in typescript. It is now ready to be integrated back into that package as a dependency. However, adding this as a dependency via npm would lead to a longer development iterations, where changes over both packages are needed and extra work in publishing intermediates to npm.

We'd like to address this by moving `thebe-core` back inside of the `thebe` repo

### Proposal

Convert the thebe repo to a monorepo and add thebe-core back in there, archiving this repo once the work is complete.

That work is in progress in https://github.com/executablebooks/thebe/pull/554

In addition to the benefits to the development experience listed here, we also benefit from keeping all `thebe` related code in the original repo, potentially moving other projects that use thebe (like sphinx-thebe) in there too in future.

### Tasks and updates

 - [x] complete the integration work
 - [ ] transfer issues to the `thebe` repo
 - [ ] archive this repo with a notice

**Comment by rowanc1** [comment]
This work is ongoing in executablebooks/thebe#554 and is working to have a monorepo rather than delete the package completely. This allows multiple entry points to thebe (headless and a default UI).
- https://github.com/executablebooks/thebe/pull/554

This in part will address:
- https://github.com/executablebooks/thebe/issues/465

**Comment by stevejpurves** [comment]
See work ongoing in https://github.com/executablebooks/thebe
